# docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    container_name: tappi_backend
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - tappi_network

  db:
    image: postgres:14-alpine
    container_name: tappi_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5469:5469"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tappi_network

networks:
  tappi_network:
    driver: bridge

volumes:
  postgres_data: